const SET_AUTH_USER = 'SET_AUTH_USER';
const UPDATE_SIDE_MENU_STATE = 'UPDATE_SIDE_MENU_STATE';
const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
const ERROR_OCCURRED = 'ERROR_OCCURRED';

export {
  GET_ALL_CATEGORIES,
  SET_AUTH_USER,
  UPDATE_SIDE_MENU_STATE,
  ERROR_OCCURRED,
};
