const ERROR_OCCURRED = 'ERROR_OCCURRED';
const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
const SET_AUTH_USER = 'SET_AUTH_USER';
const UPDATE_SIDE_MENU_STATE = 'UPDATE_SIDE_MENU_STATE';

export {
  ERROR_OCCURRED,
  GET_ALL_CATEGORIES,
  GET_PRODUCTS_LIST,
  SET_AUTH_USER,
  UPDATE_SIDE_MENU_STATE,
};
