const ERROR_OCCURRED = 'ERROR_OCCURRED';
const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
const SET_AUTH_USER = 'SET_AUTH_USER';
const UPDATE_ADDRESS_LIST = 'UPDATE_ADDRESS_LIST';
const UPDATE_CART = 'UPDATE_CART';
const UPDATE_ORDERS_LIST = 'UPDATE_ORDERS_LIST';
const UPDATE_SELECTED_ADDRESS = 'UPDATE_SELECTED_ADDRESS';
const UPDATE_SIDE_MENU_STATE = 'UPDATE_SIDE_MENU_STATE';

export {
  ERROR_OCCURRED,
  GET_ALL_CATEGORIES,
  GET_PRODUCT_DETAIL,
  GET_PRODUCTS_LIST,
  UPDATE_ORDERS_LIST,
  SET_AUTH_USER,
  UPDATE_ADDRESS_LIST,
  UPDATE_CART,
  UPDATE_SELECTED_ADDRESS,
  UPDATE_SIDE_MENU_STATE,
};
